version: '3.7'

services:

    jenkins:
        image: jenkins/jenkins:lts
        container_name: dood-jenkins
        restart: always
        networks:
            - dood_network
        ports:
            - 8090:8080
            - 5001:5000
        volumes:
            - jenkins_home:/var/jenkins_home
            - jenkins_resources:/var/resources
            - jenkins_backup:/var/jenkins_backup
        environment:
            JENKINS_OPTS: "--prefix=/jenkins -Djenkins.install.runSetupWizard=false"
            TZ: "Europe/Madrid"

volumes:
    jenkins_home:
    jenkins_resources:
    jenkins_backup:

networks:
    dood_network: